language: cpp

sudo: required
dist: eoan

services:
  - docker

matrix:
  include:
  - os: linux
    env: MATRIX_EVAL="COMPILER=g++-7"

  - os: linux
    env: MATRIX_EVAL="COMPILER=clang-8"

before_install:
  - eval "${MATRIX_EVAL}"
  - docker run -itd --name pandora -v `pwd`:/pandora/package -e "COMPILER=$COMPILER" pandorapfa/pandorapfa_c17:latest /bin/bash

script:
  - docker exec -it pandora /bin/bash -c "cd /pandora/package && source /pandora/build_pandora_pfa.sh"

notifications:
  email:
    on_success: never
    on_failure: always
